### ISSUE TITLE
Update the Cascade lake flavors for Gaia

### ISSUE THREAD

**Issue by Zarquan** [RSE-Cambridge/cumulus-config#71]
Update the Cascade lake flavors for Gaia based on new information on the available disc space (assumed 880G, actual is 830G). Rounding the numbers up/down achieve the best available fit.

The aim is to create a set of cclake* flavors that start at just under 1/2 the size of a CascadeLake hypervisor, so that 2 instances will just about fit into one hypervisor and then step down in half sizes to 1/4, 1/8, 1/16, 1/32 and 1/64 of the hypervisor.

    cumulus_gaia_cclake_55vcpu - 55vcpu, 92160M mem, 20+380G disc, fit=2
    cumulus_gaia_cclake_27vcpu - 27vcpu, 46080M mem, 20+180G disc, fit=4
    cumulus_gaia_cclake_13vcpu - 13vcpu, 23040M mem,  20+80G disc, fit=8
    cumulus_gaia_cclake_6vcpu  - 6vcpu,  10240M mem,  20+24G disc, fit=18
    cumulus_gaia_cclake_3vcpu  - 3vcpu,   5120M mem,     22G disc, fit=36
    cumulus_gaia_cclake_2vcpu  - 2vcpu,   3351M mem,     14G disc, fit=55
    cumulus_gaia_cclake_1vcpu  - 1vcpu,   1675M mem,      8G disc, fit=100

**Comment by paulbrowne** [comment]
Addressed in #72
